-- #1332 / #1371: INTEGER identity columns whose sampled join mimics CREDIT_CARD (no real card data).
-- Negative controls: ctrl_3digit (3-digit values) and ctrl_5digit (5-digit values) must not match CREDIT_CARD.
-- Requires sample_limit >= 4 on column scan for the false positive to appear.

CREATE TABLE lab_fp_numeric_ids (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001 INCREMENT BY 1) PRIMARY KEY,
    ref_a NUMBER,
    ref_b NUMBER,
    ref_c NUMBER,
    ctrl_3digit NUMBER,
    ctrl_5digit NUMBER
);

COMMENT ON TABLE lab_fp_numeric_ids IS 'Lab-only #1332 repro: joined INT samples look like CREDIT_CARD; controls are 3- and 5-digit INT columns.';

INSERT INTO lab_fp_numeric_ids (ref_a, ref_b, ref_c, ctrl_3digit, ctrl_5digit) VALUES (2001, 3001, 4001, 101, 10001);
INSERT INTO lab_fp_numeric_ids (ref_a, ref_b, ref_c, ctrl_3digit, ctrl_5digit) VALUES (2002, 3002, 4002, 102, 10002);
INSERT INTO lab_fp_numeric_ids (ref_a, ref_b, ref_c, ctrl_3digit, ctrl_5digit) VALUES (2003, 3003, 4003, 103, 10003);
INSERT INTO lab_fp_numeric_ids (ref_a, ref_b, ref_c, ctrl_3digit, ctrl_5digit) VALUES (2004, 3004, 4004, 104, 10004);
INSERT INTO lab_fp_numeric_ids (ref_a, ref_b, ref_c, ctrl_3digit, ctrl_5digit) VALUES (2005, 3005, 4005, 105, 10005);

COMMIT;
