#Requires -Version 5.1
<#
.SYNOPSIS
    Generate docs/adr/INVENTORY.txt with per-ADR SHA256 and self-attested inventory hash.

.DESCRIPTION
    Scans ADR-*.md under docs/adr/, extracts number/status/title, writes a deterministic
    audit file. Homelab secrets and product code are out of scope.

.PARAMETER AdrDir
    Directory containing ADR-*.md files. Default: docs/adr under repo root.

.PARAMETER OutFile
    Output path for INVENTORY.txt. Default: docs/adr/INVENTORY.txt.

.PARAMETER DryRun
    Compute inventory but do not write OutFile.

.EXAMPLE
    .\scripts\inv-adr.ps1
    .\scripts\inv-adr.ps1 -DryRun
#>
param(
    [string]$AdrDir = "",
    [string]$OutFile = "",
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path $PSScriptRoot -Parent
if (-not $AdrDir) {
    $AdrDir = Join-Path $repoRoot "docs\adr"
}
if (-not $OutFile) {
    $OutFile = Join-Path $AdrDir "INVENTORY.txt"
}

if (-not (Test-Path -LiteralPath $AdrDir)) {
    Write-Error "ADR directory not found: $AdrDir"
    exit 1
}

function Get-AdrStatusFromContent {
    param([string]$Raw)
    if ($Raw -match '(?m)^-\s+\*\*Status:\*\*\s*(\w+)') { return $Matches[1].Trim() }
    if ($Raw -match '\*\*Status:\*\*\s*(\w+)') { return $Matches[1].Trim() }
    return "Unknown"
}

function Get-AdrTitleFromContent {
    param([string]$Raw, [string]$FileName)
    if ($Raw -match '(?m)^#\s+ADR\s+\d{4}\s+.\s*(.+?)\s*$') {
        return $Matches[1].Trim()
    }
    return ($FileName -replace '^ADR-\d{4}-', '' -replace '\.md$', '' -replace '-', ' ')
}

$adrs = Get-ChildItem -LiteralPath $AdrDir -File -Filter "ADR-*.md" |
    Where-Object { $_.Name -match '^ADR-(\d{4})-' } |
    Sort-Object {
        [int]([regex]::Match($_.Name, '^ADR-(\d{4})-').Groups[1].Value)
    }

$dataLines = New-Object System.Collections.Generic.List[string]
foreach ($adr in $adrs) {
    $num = [regex]::Match($adr.Name, '^ADR-(\d{4})-').Groups[1].Value
    $raw = Get-Content -LiteralPath $adr.FullName -Raw -Encoding UTF8
    $title = Get-AdrTitleFromContent -Raw $raw -FileName $adr.Name
    $status = Get-AdrStatusFromContent -Raw $raw
    $norm = $raw -replace "`r`n", "`n" -replace "`r", "`n"
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($norm)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hash = [BitConverter]::ToString($sha.ComputeHash($bytes)).Replace("-", "")
    $dataLines.Add("$num | $status | $hash | $($adr.Name) | $title")
}

$utc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$header = @(
    "# ADR Inventory - generated by scripts/inv-adr.ps1"
    "# GeneratedUtc: $utc"
    "# Algorithm: SHA256"
    "# Format: NUMBER | STATUS | FILE_HASH | FILENAME | TITLE"
    "#"
)

$bodyText = ($header + $dataLines) -join "`n"
$dataOnly = $dataLines -join "`n"
$inventoryHash = (New-Object System.Security.Cryptography.SHA256Managed)
$hashBytes = [System.Text.Encoding]::UTF8.GetBytes($dataOnly)
$inventoryHashHex = [BitConverter]::ToString($inventoryHash.ComputeHash($hashBytes)).Replace("-", "")

$fullText = $bodyText + "`n#`n# InventoryHash: $inventoryHashHex`n"

if ($DryRun) {
    Write-Host "DryRun: would write $($dataLines.Count) ADR rows to $OutFile"
    Write-Host "InventoryHash: $inventoryHashHex"
    exit 0
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutFile, $fullText.Replace("`r`n", "`n").Replace("`r", "`n"), $utf8NoBom)
Write-Host "OK: $($dataLines.Count) ADRs -> $OutFile"
Write-Host "InventoryHash: $inventoryHashHex"
